//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using FZI.SoftwareEngineering.DeepModeling.TwoLevelADL;
using FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Assembly;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Deployment
{
    
    
    /// <summary>
    /// The default implementation of the Allocation class
    /// </summary>
    [XmlNamespaceAttribute("http://github.com/georghinkel/TwoLevelADL/1.0/Deployment/")]
    [XmlNamespacePrefixAttribute("deploy")]
    [ModelRepresentationClassAttribute("http://github.com/georghinkel/TwoLevelADL/1.0#//Deployment/Allocation")]
    public partial class Allocation : ModelElement, IAllocation, IModelElement
    {
        
        private static Lazy<ITypedElement> _allocationContextsReference = new Lazy<ITypedElement>(RetrieveAllocationContextsReference);
        
        /// <summary>
        /// The backing field for the AllocationContexts property
        /// </summary>
        private ObservableCompositionOrderedSet<IAllocationContext> _allocationContexts;
        
        private static Lazy<ITypedElement> _allocatedSystemReference = new Lazy<ITypedElement>(RetrieveAllocatedSystemReference);
        
        /// <summary>
        /// The backing field for the AllocatedSystem property
        /// </summary>
        private ISystem0 _allocatedSystem;
        
        private static Lazy<ITypedElement> _environmentReference = new Lazy<ITypedElement>(RetrieveEnvironmentReference);
        
        /// <summary>
        /// The backing field for the Environment property
        /// </summary>
        private IEnvironment _environment;
        
        private static IClass _classInstance;
        
        public Allocation()
        {
            this._allocationContexts = new ObservableCompositionOrderedSet<IAllocationContext>(this);
            this._allocationContexts.CollectionChanging += this.AllocationContextsCollectionChanging;
            this._allocationContexts.CollectionChanged += this.AllocationContextsCollectionChanged;
        }
        
        /// <summary>
        /// The AllocationContexts property
        /// </summary>
        [LowerBoundAttribute(1)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public IOrderedSetExpression<IAllocationContext> AllocationContexts
        {
            get
            {
                return this._allocationContexts;
            }
        }
        
        /// <summary>
        /// The AllocatedSystem property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public ISystem0 AllocatedSystem
        {
            get
            {
                return this._allocatedSystem;
            }
            set
            {
                if ((this._allocatedSystem != value))
                {
                    ISystem0 old = this._allocatedSystem;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnAllocatedSystemChanging(e);
                    this.OnPropertyChanging("AllocatedSystem", e, _allocatedSystemReference);
                    this._allocatedSystem = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetAllocatedSystem;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetAllocatedSystem;
                    }
                    this.OnAllocatedSystemChanged(e);
                    this.OnPropertyChanged("AllocatedSystem", e, _allocatedSystemReference);
                }
            }
        }
        
        /// <summary>
        /// The Environment property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public IEnvironment Environment
        {
            get
            {
                return this._environment;
            }
            set
            {
                if ((this._environment != value))
                {
                    IEnvironment old = this._environment;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnEnvironmentChanging(e);
                    this.OnPropertyChanging("Environment", e, _environmentReference);
                    this._environment = value;
                    if ((old != null))
                    {
                        old.Deleted -= this.OnResetEnvironment;
                    }
                    if ((value != null))
                    {
                        value.Deleted += this.OnResetEnvironment;
                    }
                    this.OnEnvironmentChanged(e);
                    this.OnPropertyChanged("Environment", e, _environmentReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new AllocationChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new AllocationReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://github.com/georghinkel/TwoLevelADL/1.0#//Deployment/Allocation")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the AllocatedSystem property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> AllocatedSystemChanging;
        
        /// <summary>
        /// Gets fired when the AllocatedSystem property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> AllocatedSystemChanged;
        
        /// <summary>
        /// Gets fired before the Environment property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> EnvironmentChanging;
        
        /// <summary>
        /// Gets fired when the Environment property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> EnvironmentChanged;
        
        private static ITypedElement RetrieveAllocationContextsReference()
        {
            return ((ITypedElement)(((ModelElement)(FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Deployment.Allocation.ClassInstance)).Resolve("AllocationContexts")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the AllocationContexts property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void AllocationContextsCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("AllocationContexts", e, _allocationContextsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the AllocationContexts property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void AllocationContextsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("AllocationContexts", e, _allocationContextsReference);
        }
        
        private static ITypedElement RetrieveAllocatedSystemReference()
        {
            return ((ITypedElement)(((ModelElement)(FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Deployment.Allocation.ClassInstance)).Resolve("AllocatedSystem")));
        }
        
        /// <summary>
        /// Raises the AllocatedSystemChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnAllocatedSystemChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.AllocatedSystemChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the AllocatedSystemChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnAllocatedSystemChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.AllocatedSystemChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the AllocatedSystem property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetAllocatedSystem(object sender, System.EventArgs eventArgs)
        {
            this.AllocatedSystem = null;
        }
        
        private static ITypedElement RetrieveEnvironmentReference()
        {
            return ((ITypedElement)(((ModelElement)(FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Deployment.Allocation.ClassInstance)).Resolve("Environment")));
        }
        
        /// <summary>
        /// Raises the EnvironmentChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnEnvironmentChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.EnvironmentChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the EnvironmentChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnEnvironmentChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.EnvironmentChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Environment property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetEnvironment(object sender, System.EventArgs eventArgs)
        {
            this.Environment = null;
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int allocationContextsIndex = ModelHelper.IndexOfReference(this.AllocationContexts, element);
            if ((allocationContextsIndex != -1))
            {
                return ModelHelper.CreatePath("AllocationContexts", allocationContextsIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "ALLOCATIONCONTEXTS"))
            {
                if ((index < this.AllocationContexts.Count))
                {
                    return this.AllocationContexts[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "ALLOCATIONCONTEXTS"))
            {
                return this._allocationContexts;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ALLOCATEDSYSTEM"))
            {
                this.AllocatedSystem = ((ISystem0)(value));
                return;
            }
            if ((feature == "ENVIRONMENT"))
            {
                this.Environment = ((IEnvironment)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "AllocatedSystem"))
            {
                return new AllocatedSystemProxy(this);
            }
            if ((attribute == "Environment"))
            {
                return new EnvironmentProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "AllocatedSystem"))
            {
                return new AllocatedSystemProxy(this);
            }
            if ((reference == "Environment"))
            {
                return new EnvironmentProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._allocationContexts))
            {
                return "AllocationContexts";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://github.com/georghinkel/TwoLevelADL/1.0#//Deployment/Allocation")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Allocation class
        /// </summary>
        public class AllocationChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Allocation _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public AllocationChildrenCollection(Allocation parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.AllocationContexts.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.AllocationContexts.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.AllocationContexts.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IAllocationContext allocationContextsCasted = item.As<IAllocationContext>();
                if ((allocationContextsCasted != null))
                {
                    this._parent.AllocationContexts.Add(allocationContextsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.AllocationContexts.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.AllocationContexts.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> allocationContextsEnumerator = this._parent.AllocationContexts.GetEnumerator();
                try
                {
                    for (
                    ; allocationContextsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = allocationContextsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    allocationContextsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IAllocationContext allocationContextItem = item.As<IAllocationContext>();
                if (((allocationContextItem != null) 
                            && this._parent.AllocationContexts.Remove(allocationContextItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.AllocationContexts).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Allocation class
        /// </summary>
        public class AllocationReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Allocation _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public AllocationReferencedElementsCollection(Allocation parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.AllocationContexts.Count);
                    if ((this._parent.AllocatedSystem != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.Environment != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.AllocationContexts.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.AllocatedSystemChanged += this.PropagateValueChanges;
                this._parent.EnvironmentChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.AllocationContexts.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.AllocatedSystemChanged -= this.PropagateValueChanges;
                this._parent.EnvironmentChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IAllocationContext allocationContextsCasted = item.As<IAllocationContext>();
                if ((allocationContextsCasted != null))
                {
                    this._parent.AllocationContexts.Add(allocationContextsCasted);
                }
                if ((this._parent.AllocatedSystem == null))
                {
                    ISystem0 allocatedSystemCasted = item.As<ISystem0>();
                    if ((allocatedSystemCasted != null))
                    {
                        this._parent.AllocatedSystem = allocatedSystemCasted;
                        return;
                    }
                }
                if ((this._parent.Environment == null))
                {
                    IEnvironment environmentCasted = item.As<IEnvironment>();
                    if ((environmentCasted != null))
                    {
                        this._parent.Environment = environmentCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.AllocationContexts.Clear();
                this._parent.AllocatedSystem = null;
                this._parent.Environment = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.AllocationContexts.Contains(item))
                {
                    return true;
                }
                if ((item == this._parent.AllocatedSystem))
                {
                    return true;
                }
                if ((item == this._parent.Environment))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> allocationContextsEnumerator = this._parent.AllocationContexts.GetEnumerator();
                try
                {
                    for (
                    ; allocationContextsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = allocationContextsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    allocationContextsEnumerator.Dispose();
                }
                if ((this._parent.AllocatedSystem != null))
                {
                    array[arrayIndex] = this._parent.AllocatedSystem;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.Environment != null))
                {
                    array[arrayIndex] = this._parent.Environment;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IAllocationContext allocationContextItem = item.As<IAllocationContext>();
                if (((allocationContextItem != null) 
                            && this._parent.AllocationContexts.Remove(allocationContextItem)))
                {
                    return true;
                }
                if ((this._parent.AllocatedSystem == item))
                {
                    this._parent.AllocatedSystem = null;
                    return true;
                }
                if ((this._parent.Environment == item))
                {
                    this._parent.Environment = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.AllocationContexts).Concat(this._parent.AllocatedSystem).Concat(this._parent.Environment).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the AllocatedSystem property
        /// </summary>
        private sealed class AllocatedSystemProxy : ModelPropertyChange<IAllocation, ISystem0>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public AllocatedSystemProxy(IAllocation modelElement) : 
                    base(modelElement, "AllocatedSystem")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override ISystem0 Value
            {
                get
                {
                    return this.ModelElement.AllocatedSystem;
                }
                set
                {
                    this.ModelElement.AllocatedSystem = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Environment property
        /// </summary>
        private sealed class EnvironmentProxy : ModelPropertyChange<IAllocation, IEnvironment>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public EnvironmentProxy(IAllocation modelElement) : 
                    base(modelElement, "Environment")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IEnvironment Value
            {
                get
                {
                    return this.ModelElement.Environment;
                }
                set
                {
                    this.ModelElement.Environment = value;
                }
            }
        }
    }
}

