//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using FZI.SoftwareEngineering.DeepModeling.DeepADL;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace FZI.SoftwareEngineering.DeepModeling.AssemblyX16
{
    
    
    /// <summary>
    /// The public interface for MediaStoreX16
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(MediaStoreX16))]
    [XmlDefaultImplementationTypeAttribute(typeof(MediaStoreX16))]
    public interface IMediaStoreX16 : NMF.Models.IModelElement, ISystemAllocation
    {
        
        /// <summary>
        /// The WebForm1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient1 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient1
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient2 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient2
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient3 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient3
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient4 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient4
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient5 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient5
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient6 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient6
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient7 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient7
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient8 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient8
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient9 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient9
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient10 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient10
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient11 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient11
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient12 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient12
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient13 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient13
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient14 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient14
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient15 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient15
        {
            get;
            set;
        }
        
        /// <summary>
        /// The WebForm16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer WebForm16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The AudioStore16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer AudioStore16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The UserManagement16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer UserManagement16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The EncodingAdapter16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer EncodingAdapter16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The OggEncoder16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer OggEncoder16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The DBAdapter16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer DBAdapter16
        {
            get;
            set;
        }
        
        /// <summary>
        /// The MySqlClient16 property
        /// </summary>
        [XmlAttributeAttribute(true)]
        IResourceContainer MySqlClient16
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the WebForm1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm1Changing;
        
        /// <summary>
        /// Gets fired when the WebForm1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm1Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore1Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore1Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement1Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement1Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter1Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter1Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder1Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder1Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter1Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter1Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient1 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient1Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient1 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient1Changed;
        
        /// <summary>
        /// Gets fired before the WebForm2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm2Changing;
        
        /// <summary>
        /// Gets fired when the WebForm2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm2Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore2Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore2Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement2Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement2Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter2Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter2Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder2Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder2Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter2Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter2Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient2 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient2Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient2 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient2Changed;
        
        /// <summary>
        /// Gets fired before the WebForm3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm3Changing;
        
        /// <summary>
        /// Gets fired when the WebForm3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm3Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore3Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore3Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement3Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement3Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter3Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter3Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder3Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder3Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter3Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter3Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient3 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient3Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient3 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient3Changed;
        
        /// <summary>
        /// Gets fired before the WebForm4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm4Changing;
        
        /// <summary>
        /// Gets fired when the WebForm4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm4Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore4Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore4Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement4Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement4Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter4Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter4Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder4Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder4Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter4Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter4Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient4 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient4Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient4 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient4Changed;
        
        /// <summary>
        /// Gets fired before the WebForm5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm5Changing;
        
        /// <summary>
        /// Gets fired when the WebForm5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm5Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore5Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore5Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement5Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement5Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter5Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter5Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder5Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder5Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter5Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter5Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient5 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient5Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient5 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient5Changed;
        
        /// <summary>
        /// Gets fired before the WebForm6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm6Changing;
        
        /// <summary>
        /// Gets fired when the WebForm6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm6Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore6Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore6Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement6Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement6Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter6Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter6Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder6Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder6Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter6Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter6Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient6 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient6Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient6 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient6Changed;
        
        /// <summary>
        /// Gets fired before the WebForm7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm7Changing;
        
        /// <summary>
        /// Gets fired when the WebForm7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm7Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore7Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore7Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement7Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement7Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter7Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter7Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder7Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder7Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter7Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter7Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient7 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient7Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient7 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient7Changed;
        
        /// <summary>
        /// Gets fired before the WebForm8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm8Changing;
        
        /// <summary>
        /// Gets fired when the WebForm8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm8Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore8Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore8Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement8Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement8Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter8Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter8Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder8Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder8Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter8Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter8Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient8 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient8Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient8 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient8Changed;
        
        /// <summary>
        /// Gets fired before the WebForm9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm9Changing;
        
        /// <summary>
        /// Gets fired when the WebForm9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm9Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore9Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore9Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement9Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement9Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter9Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter9Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder9Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder9Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter9Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter9Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient9 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient9Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient9 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient9Changed;
        
        /// <summary>
        /// Gets fired before the WebForm10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm10Changing;
        
        /// <summary>
        /// Gets fired when the WebForm10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm10Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore10Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore10Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement10Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement10Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter10Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter10Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder10Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder10Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter10Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter10Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient10 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient10Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient10 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient10Changed;
        
        /// <summary>
        /// Gets fired before the WebForm11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm11Changing;
        
        /// <summary>
        /// Gets fired when the WebForm11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm11Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore11Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore11Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement11Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement11Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter11Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter11Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder11Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder11Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter11Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter11Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient11 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient11Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient11 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient11Changed;
        
        /// <summary>
        /// Gets fired before the WebForm12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm12Changing;
        
        /// <summary>
        /// Gets fired when the WebForm12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm12Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore12Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore12Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement12Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement12Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter12Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter12Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder12Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder12Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter12Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter12Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient12 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient12Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient12 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient12Changed;
        
        /// <summary>
        /// Gets fired before the WebForm13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm13Changing;
        
        /// <summary>
        /// Gets fired when the WebForm13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm13Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore13Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore13Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement13Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement13Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter13Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter13Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder13Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder13Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter13Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter13Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient13 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient13Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient13 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient13Changed;
        
        /// <summary>
        /// Gets fired before the WebForm14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm14Changing;
        
        /// <summary>
        /// Gets fired when the WebForm14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm14Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore14Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore14Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement14Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement14Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter14Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter14Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder14Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder14Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter14Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter14Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient14 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient14Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient14 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient14Changed;
        
        /// <summary>
        /// Gets fired before the WebForm15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm15Changing;
        
        /// <summary>
        /// Gets fired when the WebForm15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm15Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore15Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore15Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement15Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement15Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter15Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter15Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder15Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder15Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter15Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter15Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient15 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient15Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient15 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient15Changed;
        
        /// <summary>
        /// Gets fired before the WebForm16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm16Changing;
        
        /// <summary>
        /// Gets fired when the WebForm16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> WebForm16Changed;
        
        /// <summary>
        /// Gets fired before the AudioStore16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore16Changing;
        
        /// <summary>
        /// Gets fired when the AudioStore16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> AudioStore16Changed;
        
        /// <summary>
        /// Gets fired before the UserManagement16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement16Changing;
        
        /// <summary>
        /// Gets fired when the UserManagement16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> UserManagement16Changed;
        
        /// <summary>
        /// Gets fired before the EncodingAdapter16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter16Changing;
        
        /// <summary>
        /// Gets fired when the EncodingAdapter16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EncodingAdapter16Changed;
        
        /// <summary>
        /// Gets fired before the OggEncoder16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder16Changing;
        
        /// <summary>
        /// Gets fired when the OggEncoder16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OggEncoder16Changed;
        
        /// <summary>
        /// Gets fired before the DBAdapter16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter16Changing;
        
        /// <summary>
        /// Gets fired when the DBAdapter16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DBAdapter16Changed;
        
        /// <summary>
        /// Gets fired before the MySqlClient16 property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient16Changing;
        
        /// <summary>
        /// Gets fired when the MySqlClient16 property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> MySqlClient16Changed;
    }
}

