//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace FZI.SoftwareEngineering.DeepModeling.DeepADL
{
    
    
    /// <summary>
    /// The default implementation of the Repository class
    /// </summary>
    [XmlNamespaceAttribute("http://github.com/georghinkel/DeepADL/1.0")]
    [XmlNamespacePrefixAttribute("core")]
    [ModelRepresentationClassAttribute("http://github.com/georghinkel/DeepADL/1.0#//Repository")]
    [DebuggerDisplayAttribute("Repository {Name}")]
    public partial class Repository : NMF.Models.Meta.MetaElement, IRepository, NMF.Models.IModelElement
    {
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _componentTypesReference = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveComponentTypesReference);
        
        /// <summary>
        /// The backing field for the ComponentTypes property
        /// </summary>
        private RepositoryComponentTypesCollection _componentTypes;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _interfacesReference = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveInterfacesReference);
        
        /// <summary>
        /// The backing field for the Interfaces property
        /// </summary>
        private RepositoryInterfacesCollection _interfaces;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _systemSpecificationsReference = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveSystemSpecificationsReference);
        
        /// <summary>
        /// The backing field for the SystemSpecifications property
        /// </summary>
        private RepositorySystemSpecificationsCollection _systemSpecifications;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _delegatesReference = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveDelegatesReference);
        
        /// <summary>
        /// The backing field for the Delegates property
        /// </summary>
        private RepositoryDelegatesCollection _delegates;
        
        /// <summary>
        /// The backing field for the Uri property
        /// </summary>
        private Uri _uri;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _uriAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveUriAttribute);
        
        /// <summary>
        /// The backing field for the Prefix property
        /// </summary>
        private string _prefix;
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _prefixAttribute = new Lazy<NMF.Models.Meta.ITypedElement>(RetrievePrefixAttribute);
        
        private static Lazy<NMF.Models.Meta.ITypedElement> _parentNamespaceReference = new Lazy<NMF.Models.Meta.ITypedElement>(RetrieveParentNamespaceReference);
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        public Repository()
        {
            this._componentTypes = new RepositoryComponentTypesCollection(this);
            this._componentTypes.CollectionChanging += this.ComponentTypesCollectionChanging;
            this._componentTypes.CollectionChanged += this.ComponentTypesCollectionChanged;
            this._interfaces = new RepositoryInterfacesCollection(this);
            this._interfaces.CollectionChanging += this.InterfacesCollectionChanging;
            this._interfaces.CollectionChanged += this.InterfacesCollectionChanged;
            this._systemSpecifications = new RepositorySystemSpecificationsCollection(this);
            this._systemSpecifications.CollectionChanging += this.SystemSpecificationsCollectionChanging;
            this._systemSpecifications.CollectionChanged += this.SystemSpecificationsCollectionChanged;
            this._delegates = new RepositoryDelegatesCollection(this);
            this._delegates.CollectionChanging += this.DelegatesCollectionChanging;
            this._delegates.CollectionChanged += this.DelegatesCollectionChanged;
        }
        
        /// <summary>
        /// The ComponentTypes property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("Repository")]
        [ConstantAttribute()]
        public ICollectionExpression<IComponentType> ComponentTypes
        {
            get
            {
                return this._componentTypes;
            }
        }
        
        /// <summary>
        /// The Interfaces property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("Repository")]
        [ConstantAttribute()]
        public ICollectionExpression<IInterface> Interfaces
        {
            get
            {
                return this._interfaces;
            }
        }
        
        /// <summary>
        /// The SystemSpecifications property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("Repository")]
        [ConstantAttribute()]
        public ICollectionExpression<ISystemSpecification> SystemSpecifications
        {
            get
            {
                return this._systemSpecifications;
            }
        }
        
        /// <summary>
        /// The Delegates property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("Repository")]
        [ConstantAttribute()]
        public ICollectionExpression<IDelegate> Delegates
        {
            get
            {
                return this._delegates;
            }
        }
        
        ICollectionExpression<NMF.Models.Meta.IType> NMF.Models.Meta.INamespace.Types
        {
            get
            {
                return new RepositoryTypesCollection(this);
            }
        }
        
        ICollectionExpression<NMF.Models.Meta.INamespace> NMF.Models.Meta.INamespace.ChildNamespaces
        {
            get
            {
                return EmptyList<NMF.Models.Meta.INamespace>.Instance;
            }
        }
        
        /// <summary>
        /// The Uri property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public Uri Uri
        {
            get
            {
                return this._uri;
            }
            set
            {
                if ((this._uri != value))
                {
                    Uri old = this._uri;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnUriChanging(e);
                    this.OnPropertyChanging("Uri", e, _uriAttribute);
                    this._uri = value;
                    this.OnUriChanged(e);
                    this.OnPropertyChanged("Uri", e, _uriAttribute);
                }
            }
        }
        
        /// <summary>
        /// The Prefix property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public string Prefix
        {
            get
            {
                return this._prefix;
            }
            set
            {
                if ((this._prefix != value))
                {
                    string old = this._prefix;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnPrefixChanging(e);
                    this.OnPropertyChanging("Prefix", e, _prefixAttribute);
                    this._prefix = value;
                    this.OnPrefixChanged(e);
                    this.OnPropertyChanged("Prefix", e, _prefixAttribute);
                }
            }
        }
        
        /// <summary>
        /// The ParentNamespace property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("ChildNamespaces")]
        public NMF.Models.Meta.INamespace ParentNamespace
        {
            get
            {
                return ModelHelper.CastAs<NMF.Models.Meta.INamespace>(this.Parent);
            }
            set
            {
                this.Parent = value;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<NMF.Models.IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new RepositoryChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<NMF.Models.IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new RepositoryReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://github.com/georghinkel/DeepADL/1.0#//Repository")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Uri property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> UriChanging;
        
        /// <summary>
        /// Gets fired when the Uri property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> UriChanged;
        
        /// <summary>
        /// Gets fired before the Prefix property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> PrefixChanging;
        
        /// <summary>
        /// Gets fired when the Prefix property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> PrefixChanged;
        
        /// <summary>
        /// Gets fired before the ParentNamespace property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ParentNamespaceChanging;
        
        /// <summary>
        /// Gets fired when the ParentNamespace property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ParentNamespaceChanged;
        
        private static NMF.Models.Meta.ITypedElement RetrieveComponentTypesReference()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(FZI.SoftwareEngineering.DeepModeling.DeepADL.Repository.ClassInstance)).Resolve("ComponentTypes")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the ComponentTypes property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ComponentTypesCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("ComponentTypes", e, _componentTypesReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the ComponentTypes property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ComponentTypesCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("ComponentTypes", e, _componentTypesReference);
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveInterfacesReference()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(FZI.SoftwareEngineering.DeepModeling.DeepADL.Repository.ClassInstance)).Resolve("Interfaces")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Interfaces property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void InterfacesCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("Interfaces", e, _interfacesReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Interfaces property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void InterfacesCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Interfaces", e, _interfacesReference);
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveSystemSpecificationsReference()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(FZI.SoftwareEngineering.DeepModeling.DeepADL.Repository.ClassInstance)).Resolve("SystemSpecifications")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the SystemSpecifications property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void SystemSpecificationsCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("SystemSpecifications", e, _systemSpecificationsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the SystemSpecifications property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void SystemSpecificationsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("SystemSpecifications", e, _systemSpecificationsReference);
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveDelegatesReference()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(FZI.SoftwareEngineering.DeepModeling.DeepADL.Repository.ClassInstance)).Resolve("Delegates")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Delegates property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void DelegatesCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("Delegates", e, _delegatesReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Delegates property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void DelegatesCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Delegates", e, _delegatesReference);
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveUriAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(NMF.Models.Meta.Namespace.ClassInstance)).Resolve("Uri")));
        }
        
        /// <summary>
        /// Raises the UriChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnUriChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.UriChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the UriChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnUriChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.UriChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static NMF.Models.Meta.ITypedElement RetrievePrefixAttribute()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(NMF.Models.Meta.Namespace.ClassInstance)).Resolve("Prefix")));
        }
        
        /// <summary>
        /// Raises the PrefixChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPrefixChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.PrefixChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the PrefixChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnPrefixChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.PrefixChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static NMF.Models.Meta.ITypedElement RetrieveParentNamespaceReference()
        {
            return ((NMF.Models.Meta.ITypedElement)(((NMF.Models.ModelElement)(NMF.Models.Meta.Namespace.ClassInstance)).Resolve("ParentNamespace")));
        }
        
        /// <summary>
        /// Raises the ParentNamespaceChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnParentNamespaceChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ParentNamespaceChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element is about to change
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanging(NMF.Models.IModelElement newParent, NMF.Models.IModelElement oldParent)
        {
            NMF.Models.Meta.INamespace oldParentNamespace = ModelHelper.CastAs<NMF.Models.Meta.INamespace>(oldParent);
            NMF.Models.Meta.INamespace newParentNamespace = ModelHelper.CastAs<NMF.Models.Meta.INamespace>(newParent);
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldParentNamespace, newParentNamespace);
            this.OnParentNamespaceChanging(e);
            this.OnPropertyChanging("ParentNamespace", e, _parentNamespaceReference);
        }
        
        /// <summary>
        /// Raises the ParentNamespaceChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnParentNamespaceChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ParentNamespaceChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element changes
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanged(NMF.Models.IModelElement newParent, NMF.Models.IModelElement oldParent)
        {
            NMF.Models.Meta.INamespace oldParentNamespace = ModelHelper.CastAs<NMF.Models.Meta.INamespace>(oldParent);
            NMF.Models.Meta.INamespace newParentNamespace = ModelHelper.CastAs<NMF.Models.Meta.INamespace>(newParent);
            if ((oldParentNamespace != null))
            {
                oldParentNamespace.ChildNamespaces.Remove(this);
            }
            if ((newParentNamespace != null))
            {
                newParentNamespace.ChildNamespaces.Add(this);
            }
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldParentNamespace, newParentNamespace);
            this.OnParentNamespaceChanged(e);
            this.OnPropertyChanged("ParentNamespace", e, _parentNamespaceReference);
            base.OnParentChanged(newParent, oldParent);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "URI"))
            {
                return this.Uri;
            }
            if ((attribute == "PREFIX"))
            {
                return this.Prefix;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "COMPONENTTYPES"))
            {
                return this._componentTypes;
            }
            if ((feature == "INTERFACES"))
            {
                return this._interfaces;
            }
            if ((feature == "SYSTEMSPECIFICATIONS"))
            {
                return this._systemSpecifications;
            }
            if ((feature == "DELEGATES"))
            {
                return this._delegates;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "PARENTNAMESPACE"))
            {
                this.ParentNamespace = ((NMF.Models.Meta.INamespace)(value));
                return;
            }
            if ((feature == "URI"))
            {
                this.Uri = ((Uri)(value));
                return;
            }
            if ((feature == "PREFIX"))
            {
                this.Prefix = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "ParentNamespace"))
            {
                return new ParentNamespaceProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "ParentNamespace"))
            {
                return new ParentNamespaceProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._componentTypes))
            {
                return "ComponentTypes";
            }
            if ((container == this._interfaces))
            {
                return "Interfaces";
            }
            if ((container == this._systemSpecifications))
            {
                return "SystemSpecifications";
            }
            if ((container == this._delegates))
            {
                return "Delegates";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://github.com/georghinkel/DeepADL/1.0#//Repository")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Repository class
        /// </summary>
        public class RepositoryChildrenCollection : ReferenceCollection, ICollectionExpression<NMF.Models.IModelElement>, ICollection<NMF.Models.IModelElement>
        {
            
            private Repository _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public RepositoryChildrenCollection(Repository parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.ComponentTypes.Count);
                    count = (count + this._parent.Interfaces.Count);
                    count = (count + this._parent.SystemSpecifications.Count);
                    count = (count + this._parent.Delegates.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.ComponentTypes.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Interfaces.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.SystemSpecifications.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Delegates.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.ComponentTypes.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Interfaces.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.SystemSpecifications.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Delegates.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(NMF.Models.IModelElement item)
            {
                IComponentType componentTypesCasted = item.As<IComponentType>();
                if ((componentTypesCasted != null))
                {
                    this._parent.ComponentTypes.Add(componentTypesCasted);
                }
                IInterface interfacesCasted = item.As<IInterface>();
                if ((interfacesCasted != null))
                {
                    this._parent.Interfaces.Add(interfacesCasted);
                }
                ISystemSpecification systemSpecificationsCasted = item.As<ISystemSpecification>();
                if ((systemSpecificationsCasted != null))
                {
                    this._parent.SystemSpecifications.Add(systemSpecificationsCasted);
                }
                IDelegate delegatesCasted = item.As<IDelegate>();
                if ((delegatesCasted != null))
                {
                    this._parent.Delegates.Add(delegatesCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.ComponentTypes.Clear();
                this._parent.Interfaces.Clear();
                this._parent.SystemSpecifications.Clear();
                this._parent.Delegates.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(NMF.Models.IModelElement item)
            {
                if (this._parent.ComponentTypes.Contains(item))
                {
                    return true;
                }
                if (this._parent.Interfaces.Contains(item))
                {
                    return true;
                }
                if (this._parent.SystemSpecifications.Contains(item))
                {
                    return true;
                }
                if (this._parent.Delegates.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(NMF.Models.IModelElement[] array, int arrayIndex)
            {
                IEnumerator<NMF.Models.IModelElement> componentTypesEnumerator = this._parent.ComponentTypes.GetEnumerator();
                try
                {
                    for (
                    ; componentTypesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = componentTypesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    componentTypesEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> interfacesEnumerator = this._parent.Interfaces.GetEnumerator();
                try
                {
                    for (
                    ; interfacesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = interfacesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    interfacesEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> systemSpecificationsEnumerator = this._parent.SystemSpecifications.GetEnumerator();
                try
                {
                    for (
                    ; systemSpecificationsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = systemSpecificationsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    systemSpecificationsEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> delegatesEnumerator = this._parent.Delegates.GetEnumerator();
                try
                {
                    for (
                    ; delegatesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = delegatesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    delegatesEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(NMF.Models.IModelElement item)
            {
                IComponentType componentTypeItem = item.As<IComponentType>();
                if (((componentTypeItem != null) 
                            && this._parent.ComponentTypes.Remove(componentTypeItem)))
                {
                    return true;
                }
                IInterface interfaceItem = item.As<IInterface>();
                if (((interfaceItem != null) 
                            && this._parent.Interfaces.Remove(interfaceItem)))
                {
                    return true;
                }
                ISystemSpecification systemSpecificationItem = item.As<ISystemSpecification>();
                if (((systemSpecificationItem != null) 
                            && this._parent.SystemSpecifications.Remove(systemSpecificationItem)))
                {
                    return true;
                }
                IDelegate delegateItem = item.As<IDelegate>();
                if (((delegateItem != null) 
                            && this._parent.Delegates.Remove(delegateItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<NMF.Models.IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<NMF.Models.IModelElement>().Concat(this._parent.ComponentTypes).Concat(this._parent.Interfaces).Concat(this._parent.SystemSpecifications).Concat(this._parent.Delegates).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Repository class
        /// </summary>
        public class RepositoryReferencedElementsCollection : ReferenceCollection, ICollectionExpression<NMF.Models.IModelElement>, ICollection<NMF.Models.IModelElement>
        {
            
            private Repository _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public RepositoryReferencedElementsCollection(Repository parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.ComponentTypes.Count);
                    count = (count + this._parent.Interfaces.Count);
                    count = (count + this._parent.SystemSpecifications.Count);
                    count = (count + this._parent.Delegates.Count);
                    if ((this._parent.ParentNamespace != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.ComponentTypes.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Interfaces.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.SystemSpecifications.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Delegates.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.ParentNamespaceChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.ComponentTypes.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Interfaces.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.SystemSpecifications.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Delegates.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.ParentNamespaceChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(NMF.Models.IModelElement item)
            {
                IComponentType componentTypesCasted = item.As<IComponentType>();
                if ((componentTypesCasted != null))
                {
                    this._parent.ComponentTypes.Add(componentTypesCasted);
                }
                IInterface interfacesCasted = item.As<IInterface>();
                if ((interfacesCasted != null))
                {
                    this._parent.Interfaces.Add(interfacesCasted);
                }
                ISystemSpecification systemSpecificationsCasted = item.As<ISystemSpecification>();
                if ((systemSpecificationsCasted != null))
                {
                    this._parent.SystemSpecifications.Add(systemSpecificationsCasted);
                }
                IDelegate delegatesCasted = item.As<IDelegate>();
                if ((delegatesCasted != null))
                {
                    this._parent.Delegates.Add(delegatesCasted);
                }
                if ((this._parent.ParentNamespace == null))
                {
                    NMF.Models.Meta.INamespace parentNamespaceCasted = item.As<NMF.Models.Meta.INamespace>();
                    if ((parentNamespaceCasted != null))
                    {
                        this._parent.ParentNamespace = parentNamespaceCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.ComponentTypes.Clear();
                this._parent.Interfaces.Clear();
                this._parent.SystemSpecifications.Clear();
                this._parent.Delegates.Clear();
                this._parent.ParentNamespace = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(NMF.Models.IModelElement item)
            {
                if (this._parent.ComponentTypes.Contains(item))
                {
                    return true;
                }
                if (this._parent.Interfaces.Contains(item))
                {
                    return true;
                }
                if (this._parent.SystemSpecifications.Contains(item))
                {
                    return true;
                }
                if (this._parent.Delegates.Contains(item))
                {
                    return true;
                }
                if ((item == this._parent.ParentNamespace))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(NMF.Models.IModelElement[] array, int arrayIndex)
            {
                IEnumerator<NMF.Models.IModelElement> componentTypesEnumerator = this._parent.ComponentTypes.GetEnumerator();
                try
                {
                    for (
                    ; componentTypesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = componentTypesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    componentTypesEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> interfacesEnumerator = this._parent.Interfaces.GetEnumerator();
                try
                {
                    for (
                    ; interfacesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = interfacesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    interfacesEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> systemSpecificationsEnumerator = this._parent.SystemSpecifications.GetEnumerator();
                try
                {
                    for (
                    ; systemSpecificationsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = systemSpecificationsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    systemSpecificationsEnumerator.Dispose();
                }
                IEnumerator<NMF.Models.IModelElement> delegatesEnumerator = this._parent.Delegates.GetEnumerator();
                try
                {
                    for (
                    ; delegatesEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = delegatesEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    delegatesEnumerator.Dispose();
                }
                if ((this._parent.ParentNamespace != null))
                {
                    array[arrayIndex] = this._parent.ParentNamespace;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(NMF.Models.IModelElement item)
            {
                IComponentType componentTypeItem = item.As<IComponentType>();
                if (((componentTypeItem != null) 
                            && this._parent.ComponentTypes.Remove(componentTypeItem)))
                {
                    return true;
                }
                IInterface interfaceItem = item.As<IInterface>();
                if (((interfaceItem != null) 
                            && this._parent.Interfaces.Remove(interfaceItem)))
                {
                    return true;
                }
                ISystemSpecification systemSpecificationItem = item.As<ISystemSpecification>();
                if (((systemSpecificationItem != null) 
                            && this._parent.SystemSpecifications.Remove(systemSpecificationItem)))
                {
                    return true;
                }
                IDelegate delegateItem = item.As<IDelegate>();
                if (((delegateItem != null) 
                            && this._parent.Delegates.Remove(delegateItem)))
                {
                    return true;
                }
                if ((this._parent.ParentNamespace == item))
                {
                    this._parent.ParentNamespace = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<NMF.Models.IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<NMF.Models.IModelElement>().Concat(this._parent.ComponentTypes).Concat(this._parent.Interfaces).Concat(this._parent.SystemSpecifications).Concat(this._parent.Delegates).Concat(this._parent.ParentNamespace).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Uri property
        /// </summary>
        private sealed class UriProxy : ModelPropertyChange<NMF.Models.Meta.INamespace, Uri>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public UriProxy(NMF.Models.Meta.INamespace modelElement) : 
                    base(modelElement, "Uri")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override Uri Value
            {
                get
                {
                    return this.ModelElement.Uri;
                }
                set
                {
                    this.ModelElement.Uri = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Prefix property
        /// </summary>
        private sealed class PrefixProxy : ModelPropertyChange<NMF.Models.Meta.INamespace, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public PrefixProxy(NMF.Models.Meta.INamespace modelElement) : 
                    base(modelElement, "Prefix")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Prefix;
                }
                set
                {
                    this.ModelElement.Prefix = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the ParentNamespace property
        /// </summary>
        private sealed class ParentNamespaceProxy : ModelPropertyChange<NMF.Models.Meta.INamespace, NMF.Models.Meta.INamespace>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ParentNamespaceProxy(NMF.Models.Meta.INamespace modelElement) : 
                    base(modelElement, "ParentNamespace")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override NMF.Models.Meta.INamespace Value
            {
                get
                {
                    return this.ModelElement.ParentNamespace;
                }
                set
                {
                    this.ModelElement.ParentNamespace = value;
                }
            }
        }
    }
}

