//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using FZI.SoftwareEngineering.DeepModeling.TwoLevelADL;
using FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.SystemIndependent;
using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.Assembly
{
    
    
    /// <summary>
    /// The public interface for CompositeComponent
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(CompositeComponent))]
    [XmlDefaultImplementationTypeAttribute(typeof(CompositeComponent))]
    public interface ICompositeComponent : IModelElement, FZI.SoftwareEngineering.DeepModeling.TwoLevelADL.SystemIndependent.IComponent
    {
        
        /// <summary>
        /// The EncapsulatedContexts property
        /// </summary>
        IOrderedSetExpression<IAssemblyContext> EncapsulatedContexts
        {
            get;
        }
        
        /// <summary>
        /// The DelegateConnectors property
        /// </summary>
        IOrderedSetExpression<IDelegateConnector> DelegateConnectors
        {
            get;
        }
        
        /// <summary>
        /// The Connectors property
        /// </summary>
        IOrderedSetExpression<IAssemblyConnector> Connectors
        {
            get;
        }
    }
}

